name: trimmomatic
on: [push]

jobs: 
  trimmomatic:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: install trimmomatic
      run: |
        conda install -y -c bioconda trimmomatic
        echo "$CONDA/bin" >> $GITHUB_PATH
        ls -R $CONDA
    - name: Run trimmomatic
      run: |
        trimmomatic PE -phred33 testdata/ERR5556343_1.fastq.gz testdata/ERR5556343_2.fastq.gz R1.paired.fastq.gz R1.unpaired.fastq.gz R2.paired.fastq.gz R2.unpaired.fastq.gz ILLUMINACLIP:adapters/TruSeq2-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
        for i in R1.paired.fastq.gz R1.unpaired.fastq.gz R2.paired.fastq.gz R2.unpaired.fastq.gz; do echo $i; zcat $i | head -n 8; done
        ls -lh R1.paired.fastq.gz R1.unpaired.fastq.gz R2.paired.fastq.gz R2.unpaired.fastq.gz
